import './globals.css'
import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/lib/registry'
import { Providers } from './providers'
import { open_sans } from '@/styles/fonts'

export const metadata: Metadata = {
  title: 'Boilerplate V3',
  description: 'Generated by Julio Carneiro'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className} suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
