name: Production Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    stage: build
    artifacts:
    paths:
      - build/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Linting
      run: yarn lint

    - name: Security
      run: yarn protect

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

  deploy:
    stage: deploy
    only:
      - master
    image: python:latest
    dependencies:
      - build
    script:
      - pip install awscli
      - aws s3 cp build/ s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}/ --recursive --include "*"
